'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Search, ShieldCheck, ArrowRight, FileCheck2, Info } from 'lucide-react'
import { Logo } from '@/components/ui/Logo'
import { Button } from '@/components/ui/Button'

export default function VerifySearchPage() {
  const [receiptId, setReceiptId] = useState('')
  const router = useRouter()

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (receiptId.trim()) {
      router.push(`/verify/${receiptId.trim().toUpperCase()}`)
    }
  }

  return (
    <div className="min-h-screen bg-paper-100 text-ink-900 flex flex-col">
      {/* ── Nav ──────────────────────────────────────────── */}
      <nav className="border-b border-ink-900/10 bg-paper-50/50 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto max-w-7xl px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <Logo iconOnly size="sm" />
            <span className="font-display text-sm font-bold uppercase tracking-widest text-ink-900">
              RentProof
            </span>
          </Link>
          <div className="hidden md:block text-[10px] font-bold uppercase tracking-[0.2em] text-ink-400 font-mono">
            SECURE-VERIFICATION-v1.02
          </div>
        </div>
      </nav>

      <main className="flex-1 flex flex-col items-center justify-center px-6 py-20">
        <div className="w-full max-w-2xl">
          <header className="text-center mb-16">
            <div className="mb-6 inline-flex items-center gap-2 px-3 py-1 border border-ink-900/10 text-[10px] font-bold uppercase tracking-widest text-brand-600 font-mono">
              <ShieldCheck className="h-3 w-3" />
              Public Protocol Audit
            </div>
            <h1 className="font-display text-5xl font-bold tracking-tight mb-6">
              Verify Transaction <span className="italic">Integrity.</span>
            </h1>
            <p className="text-lg font-medium text-ink-600 leading-relaxed max-w-lg mx-auto">
              Enter a unique RentProof Receipt ID to audit the mutual 
              acknowledgment status of a rent payment.
            </p>
          </header>

          <form onSubmit={handleSubmit} className="relative group">
            <div className="absolute -inset-1 bg-ink-900/5 blur opacity-25 group-focus-within:opacity-100 transition-opacity" />
            <div className="relative flex flex-col sm:flex-row shadow-2xl">
              <div className="absolute inset-y-0 left-0 pl-6 flex items-center pointer-events-none z-10">
                <Search className="h-5 w-5 text-ink-400" />
              </div>
              <input
                type="text"
                value={receiptId}
                onChange={(e) => setReceiptId(e.target.value)}
                placeholder="RP-XXXXXX"
                className="block w-full pl-16 pr-6 sm:pr-44 py-8 bg-paper-50 border-2 border-ink-900/10 focus:border-ink-900 focus:outline-none text-xl sm:text-2xl font-display font-bold tracking-widest placeholder:text-ink-200 transition-all uppercase"
                autoFocus
              />
              <div className="sm:absolute sm:inset-y-3 sm:right-3 p-3 sm:p-0 bg-paper-50 sm:bg-transparent">
                <Button 
                  type="submit" 
                  size="lg" 
                  disabled={!receiptId.trim()}
                  className="w-full sm:w-auto h-14 sm:h-full rounded-none px-10 bg-ink-900 hover:bg-ink-800 border-none text-[11px] font-bold uppercase tracking-widest"
                >
                  Verify Audit
                  <ArrowRight className="h-4 w-4 ml-2" />
                </Button>
              </div>
            </div>
          </form>

          <div className="mt-16 grid gap-8 md:grid-cols-2">
            <div className="p-8 border border-ink-900/5 bg-paper-50/50">
              <div className="mb-4 flex items-center gap-3">
                <FileCheck2 className="h-4 w-4 text-brand-600" />
                <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-ink-900">Institutional Standard</h3>
              </div>
              <p className="text-sm font-medium text-ink-600 leading-relaxed">
                Receipts generated by the protocol are structured for 
                tribunal admissibility and institutional archival.
              </p>
              <Link href="/verify/demo" className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-ink-900 group">
                View Sample Audit Record
                <ArrowRight className="h-3 w-3 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>

            <div className="p-8 border border-ink-900/5 bg-paper-50/50">
              <div className="mb-4 flex items-center gap-3">
                <Info className="h-4 w-4 text-ink-900" />
                <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-ink-900">How it Works</h3>
              </div>
              <ul className="space-y-3">
                {[
                  'Enter 8-digit alpha-numeric ID',
                  'Audit status and timestamps',
                  'Verify counterparty validation',
                  'Export official protocol records'
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2 text-[10px] font-bold text-ink-500 uppercase tracking-wide">
                    <span className="h-1.5 w-1.5 bg-ink-300" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </main>

      {/* ── Footer ────────────────────────────────────────── */}
      <footer className="border-t border-ink-900/10 py-10 bg-paper-100">
        <div className="mx-auto max-w-7xl px-6 flex flex-col md:flex-row items-center justify-between gap-6">
          <p className="text-[10px] font-bold uppercase tracking-widest text-ink-400">
            RentProof Verification Protocol <span className="font-mono opacity-50 px-2">{"//"}</span> v1.02
          </p>
          <div className="flex gap-8">
            <Link href="/terms-of-service" className="text-[10px] font-bold uppercase tracking-widest text-ink-500 hover:text-ink-900 transition-colors">Terms of Service</Link>
            <Link href="/privacy-policy" className="text-[10px] font-bold uppercase tracking-widest text-ink-500 hover:text-ink-900 transition-colors">Privacy Policy</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
